server:
  port: 9002
spring:
  application:
    name: ScientificResearch-system
    datasourse:
      driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.47.128:3306/ScientificResearch_system?useUnicode=true&amp;characterEncoding=UTF-8?autoReconnect=true
        username: root
        password: root
    jpa:
      database: mysql
      #    hibernate:
      #      ddl-auto: update
      show-sql: true